apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-app
  template:
    metadata:
      labels:
        app: backend-app
    spec:
      containers:
      - name: backend-container
        image: 659194519955.dkr.ecr.us-east-1.amazonaws.com/backend-repo:latest
        ports:
        - containerPort: 3001

---

apiVersion: v1
kind: Service
metadata:
  name: backend-deployment
spec:
  selector:
    app: backend-app
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3001
  externalIPs:
    - 10.0.0.1

